#!/usr/bin/env python3
"""Generate all 10 CS50 AI lecture lesson.json files following the Python module pattern."""
import json
import os

BASE = "frontend/public/data/cs50ai"


def exp(title, body, bullets=None, accent="blue"):
    b = {"type": "explanation", "accentColor": accent, "title": title, "body": body}
    if bullets:
        b["bullets"] = bullets
    return b


def analogy(title, text, emoji=""):
    return {"type": "analogy", "title": title, "emoji": emoji, "text": text}


def viz(title, accent, left, center_label, center_text=None, flow_steps=None, code=None, output=None):
    center = {"label": center_label, "visualType": "flow_diagram" if flow_steps else "text",
              "flowSteps": flow_steps, "textContent": center_text}
    right = {"label": "Code Example", "code": code or "# See example above", "language": "python", "output": output or ""}
    return {"type": "concept_visualization", "title": title, "accentColor": accent,
            "leftPanel": left, "centerPanel": center, "rightPanel": right}


def refl(question, answer, code=None, output=None):
    r = {"type": "reflection", "question": question, "answer": answer}
    if code:
        r["followupCode"] = code
    if output:
        r["followupOutput"] = output
    return r


def code_ex(title, c, output):
    return {"type": "code_example", "title": title, "language": "python", "code": c, "expectedOutput": output}


def practice(title, instructions, starter, solution, hint):
    return {"type": "practice", "title": title, "instructions": instructions,
            "starterCode": starter, "solution": solution, "hint": hint}


def left_panel(emoji, title, desc):
    return {"label": "Real Life Analogy", "emoji": emoji, "title": title, "description": desc}


def write_lesson(num, data):
    path = os.path.join(BASE, f"lecture_{num}", "lesson.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {path}")


def lesson_meta(num, title, overview, minutes, next_up):
    return {
        "id": f"cs50ai-lecture-{num}",
        "courseSlug": "cs50ai",
        "number": num,
        "title": title,
        "overview": overview,
        "estimatedMinutes": minutes,
        "nextUp": next_up,
    }


LECTURES = []

# ── Lecture 0: Introduction to AI ──────────────────────────────────────────
LECTURES.append({
    **lesson_meta(0, "Introduction to AI",
        "Artificial Intelligence is everywhere — from spam filters to voice assistants. "
        "Learn what AI is, how it relates to ML and Deep Learning, and where you'll encounter it daily.",
        50, "Search Algorithms"),
    "sections": [
        {"id": "what-is-ai", "label": "What is AI?", "blocks": [
            exp("What is Artificial Intelligence?",
                "**Artificial Intelligence (AI)** is the field of computer science focused on building systems that perform tasks normally requiring human thinking — learning, reasoning, recognizing patterns, and making decisions.",
                ["Computers performing tasks that need human intelligence",
                 "Examples: playing chess, recognizing faces, translating languages",
                 "AI powers spam filters, voice assistants, and recommendation systems",
                 "Not about robots — about intelligent problem-solving"]),
            analogy("Think of AI as a Very Fast, Tireless Assistant",
                    "Imagine an assistant who never sleeps, processes millions of examples instantly, and follows rules or learns from examples. That's AI — you give it data or instructions, and it performs tasks intelligently."),
            viz("AI: Computers That Think", "blue",
                left_panel("🤖", "Smart Assistant", "Fast, tireless, learns from examples"),
                "Programming Concept",
                "Computers performing tasks that require human-like thinking:\n• Playing chess\n• Recognizing faces\n• Filtering spam\n• Recommending movies",
                code="# AI in daily life\n# Gmail spam filter\n# Google Maps routing\n# Netflix recommendations\n# Siri / Alexa\nprint('AI is everywhere!')", output="All powered by AI!"),
            refl("Is a basic calculator an AI system? Why or why not?",
                 "No. A calculator follows fixed programmed rules (add, subtract). AI adapts, learns, or makes decisions beyond explicit programming. A spam filter IS AI because it learns from examples.",
                 "# Calculator: NOT AI\nresult = 5 + 3\n\n# Spam filter: IS AI\n# Learns from examples, adapts to new spam",
                 "Calculator: 8\nAI adapts over time"),
        ]},
        {"id": "ai-ml-dl", "label": "AI vs ML vs DL", "blocks": [
            exp("AI vs Machine Learning vs Deep Learning",
                "These three terms are related but describe different levels of the AI field.",
                ["**AI** — broadest umbrella: any technique making computers appear intelligent",
                 "**Machine Learning (ML)** — subset of AI: learns rules from data instead of being programmed",
                 "**Deep Learning (DL)** — subset of ML: uses brain-like neural networks with many layers"]),
            analogy("Think of ML as Teaching a Dog Tricks",
                    "You don't write every rule — you show examples and reward correct behavior. The dog learns patterns. ML works the same way: show data, let the computer find patterns."),
            viz("The AI Hierarchy", "purple",
                left_panel("🐕", "Teaching by Reward", "Show examples, reward correct behavior"),
                "Nested Categories",
                "AI (broadest)\n  └── Machine Learning\n        └── Deep Learning (neural networks)",
                code="# Hierarchy check\nterm = 'neural network layers'\nif 'layer' in term:\n    print('Deep Learning')\n    print('Also ML and AI')", output="Deep Learning\nAlso ML and AI"),
            exp("Narrow AI vs General AI",
                "All AI today is **Narrow AI** — it excels at one specific task. **General AI** (capable of any intellectual task) remains theoretical.",
                ["Narrow AI: chess engines, spam filters, voice assistants",
                 "General AI: would excel at any task like a human — we don't have this yet",
                 "Every AI system you use today is Narrow AI"]),
            analogy("Think of DL as Layers in the Human Eye",
                    "Your eye has layers of cells — each layer detects edges, shapes, then objects. Deep Learning uses similar layered processing to understand complex data like images."),
            viz("Narrow vs General AI", "purple",
                left_panel("♟️", "The Specialist", "Excels at one task, can't do everything"),
                "Today's AI",
                "Narrow AI (Today):\n✓ Chess engine\n✓ Spam filter\n✓ Voice assistant\n✓ Face recognition\n\nGeneral AI: Not yet!",
                code="# Narrow AI example\nai_task = 'recommend movies'\n# Can ONLY do this one task well\nprint(f'AI specializes in: {ai_task}')", output="AI specializes in: recommend movies"),
            refl("Which is the broadest term: AI, ML, or DL?",
                 "AI is the broadest. ML is a subset of AI. DL is a subset of ML. Think of nesting dolls — AI contains ML contains DL."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("AI in the Real World",
                "AI isn't future technology — it's already embedded in tools you use every day.",
                ["**Spam filters** — learn which emails are junk from millions of examples",
                 "**Google Maps** — uses search and optimization to find fastest routes",
                 "**Netflix** — recommends shows using machine learning on your history",
                 "**Voice assistants** — understand speech using NLP and ML"]),
            viz("How AI Works in Practice", "green",
                left_panel("📱", "Daily Tools", "Maps, music, email, shopping"),
                "Step-by-Step Flow",
                None,
                code="# Step 1: Collect data\n# Step 2: Train a model\n# Step 3: Make predictions\nprint('Data → Model → Prediction')", output="Data → Model → Prediction"),
            {"type": "concept_visualization", "title": "The AI Pipeline", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "📊", "title": "Collect Data", "description": "Gather examples the AI can learn from"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Collect Data", "↓", "Train Model", "↓", "Make Predictions"]},
             "rightPanel": {"label": "Step 3", "emoji": "🎯", "title": "Use AI", "description": "The trained model makes intelligent decisions on new inputs"}},
            exp("The CS50 AI Journey",
                "This course covers 7 core AI topics you'll explore in upcoming lectures.",
                ["**Search** — finding paths from start to goal (GPS, puzzles)",
                 "**Knowledge** — representing facts and reasoning with logic",
                 "**Uncertainty** — handling probability when information is incomplete",
                 "**Optimization** — finding the best solution among many options",
                 "**Learning** — ML from labeled and unlabeled data",
                 "**Neural Networks** — brain-inspired computing for deep learning",
                 "**Language** — NLP and large language models like GPT"]),
            refl("Which AI topic would a voice assistant like Alexa use?",
                 "Multiple! NLP to understand speech, ML to personalize responses, Search to find answers, and Uncertainty to handle ambiguous requests. Real AI combines many techniques."),
            practice("Identify AI Around You",
                     "Write a Python program that prints 3 AI tools you use daily and one sentence about what each does.",
                     "# List 3 AI tools you use\nprint('1. ')\nprint('2. ')\nprint('3. ')",
                     "print('1. Google Maps - finds fastest routes using search')\nprint('2. Spotify - recommends songs using ML')\nprint('3. Gmail - filters spam using AI')",
                     "Think about apps on your phone. Each print() should name the tool and its AI task."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "AI = computers doing tasks that need human thinking"},
        {"emoji": "", "text": "ML is a subset of AI that learns from data"},
        {"emoji": "", "text": "Deep Learning uses neural networks inspired by the brain"},
        {"emoji": "", "text": "All AI today is Narrow AI — it does one specific task"},
        {"emoji": "", "text": "AI is already in your daily life: maps, music, email filters"},
        {"emoji": "", "text": "The CS50 AI path covers: Search, Knowledge, Uncertainty, Optimization, Learning, Neural Nets, Language"},
    ],
    "whatYouLearned": [
        "What Artificial Intelligence really means",
        "How Machine Learning and Deep Learning relate to AI",
        "The difference between Narrow AI and General AI",
        "Real examples of AI you encounter every day",
        "The 7 core AI topics in this course",
        "How AI systems collect data, train models, and make predictions",
    ],
})

# ── Lecture 1: Search Algorithms ───────────────────────────────────────────
LECTURES.append({
    **lesson_meta(1, "Search Algorithms",
        "Search is foundational in AI — finding a path from start to goal. Learn BFS, DFS, Greedy Best-First, and A* search.",
        55, "Knowledge & Logic"),
    "sections": [
        {"id": "search-problem", "label": "What is a Search Problem?", "blocks": [
            exp("What is a Search Problem?",
                "A **search problem** involves an agent moving from an **initial state** to a **goal state** by taking **actions** through a **state space** (all possible configurations).",
                ["Start state — where you begin",
                 "Goal state — where you want to arrive",
                 "Actions — valid moves from each state",
                 "Path cost — how expensive a solution is"]),
            analogy("Think of Navigating a Maze",
                    "Your position is your state. Walls limit your actions (movements). Finding a path from entrance to exit is the search problem."),
            viz("Search Problem Components", "blue",
                left_panel("🗺️", "GPS Navigation", "Start → follow roads → reach destination"),
                "Search Components",
                "Initial State = Starting point\nActions = Valid moves\nGoal State = Destination\nPath Cost = Distance or time",
                code="# Search problem example\nstart = 'Home'\ngoal = 'School'\nactions = ['North', 'South', 'East', 'West']\nprint(f'Find path: {start} → {goal}')", output="Find path: Home → School"),
            refl("In a maze, what is the goal state called?",
                 "The goal state is the destination — the configuration you want to reach. In a maze, it's typically the exit cell marked G."),
        ]},
        {"id": "bfs-dfs", "label": "BFS & DFS", "blocks": [
            exp("Breadth-First Search (BFS)",
                "**BFS** explores all neighbors at the current level before going deeper — like ripples spreading in water. It uses a queue (FIFO) and **guarantees the shortest path**.",
                ["Explores level by level — all nearby options first",
                 "Uses a queue: first discovered, first explored",
                 "Guarantees shortest path in unweighted graphs",
                 "Uses more memory than DFS"]),
            exp("Depth-First Search (DFS)",
                "**DFS** goes deep into one path before backtracking — like following one corridor to the end. It uses a stack (LIFO) and uses **less memory** but may not find the shortest path.",
                ["Explores one branch fully before trying others",
                 "Uses a stack: last discovered, first explored",
                 "Less memory than BFS",
                 "Does not guarantee shortest path"]),
            analogy("BFS = Checking Every Shelf on Floor 1 First",
                    "Before going to Floor 2, BFS checks every store on Floor 1. DFS is like going deep into one hallway, exploring all side rooms before backtracking."),
            viz("BFS vs DFS", "purple",
                left_panel("🏪", "Floor-by-Floor vs Deep Exploration", "BFS: systematic levels. DFS: deep then backtrack."),
                "Algorithm Comparison",
                "BFS:\n• Queue (FIFO)\n• Shortest path ✓\n• More memory\n\nDFS:\n• Stack (LIFO)\n• Less memory\n• No shortest guarantee",
                code="from collections import deque\n# BFS: queue.popleft()\n# DFS: stack.pop()", output="BFS: level by level\nDFS: deep first"),
            refl("Which search guarantees the shortest path?",
                 "BFS guarantees the shortest path because it explores all nodes at distance 1, then distance 2, and so on. The first path to the goal is always the shortest."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Greedy Best-First & A* Search",
                "**Greedy Best-First** uses a heuristic (estimate) to pick the most promising next step. **A*** combines actual cost so far g(n) AND estimated cost h(n) — making it both optimal and efficient.",
                ["Heuristic h(n) — estimated cost from current node to goal",
                 "Greedy uses only h(n) — can be fast but not optimal",
                 "A* uses f(n) = g(n) + h(n) — cost so far + estimate",
                 "A* is used in GPS navigation and game AI"]),
            analogy("A* = GPS That Considers Distance Traveled AND Estimated Distance",
                    "GPS doesn't explore blindly. It considers how far you've driven AND estimates remaining distance — just like A* combines g(n) and h(n)."),
            {"type": "concept_visualization", "title": "How A* Search Works", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "📍", "title": "Start at Initial State", "description": "Begin with g(n)=0, estimate h(n) to goal"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Pick lowest f(n)", "↓", "Expand neighbors", "↓", "Reach goal state"]},
             "rightPanel": {"label": "Code Example", "code": "# A* formula\nf_n = g_n + h_n\n# g_n = cost so far\n# h_n = estimate to goal\nprint(f'f(n) = {f_n}')", "language": "python", "output": "A*: Optimal + Fast!"}},
            code_ex("Graph as Dictionary",
                 "graph = {\n    'A': ['B', 'C'],\n    'B': ['A', 'D'],\n    'C': ['A'],\n    'D': ['B']\n}\nnode = 'B'\nprint(f'Neighbors of {node}: {graph[node]}')",
                 "Neighbors of B: ['A', 'D']"),
            refl("What does A* use that Greedy Best-First does not?",
                 "A* uses BOTH cost so far (g(n)) AND estimated cost to goal (h(n)). Greedy only uses the heuristic h(n), ignoring how far you've already traveled."),
            practice("Explore a Simple Graph",
                     "Create a dictionary representing a graph with at least 4 nodes. Print all neighbors of a given node.",
                     "# Define your graph\ngraph = {\n    'A': ['B', 'C'],\n}\nnode = 'A'\n# Print neighbors",
                     "graph = {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A'], 'D': ['B']}\nnode = 'B'\nprint(f'Neighbors of {node}: {graph[node]}')",
                     "Use graph[node] to access the list of neighbors for any node."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "A search problem has a start state, actions, and a goal state"},
        {"emoji": "", "text": "BFS finds the shortest path by exploring level by level"},
        {"emoji": "", "text": "DFS goes deep first — uses less memory but may not find shortest path"},
        {"emoji": "", "text": "Greedy search uses a heuristic to pick the best next step"},
        {"emoji": "", "text": "A* combines cost so far + estimated cost = most efficient search"},
        {"emoji": "", "text": "Search is used in maps, games, puzzles, and route planning"},
    ],
    "whatYouLearned": [
        "How to model a problem as a search problem",
        "The difference between BFS and DFS",
        "How heuristics improve search efficiency",
        "How A* achieves optimal solutions",
        "When to choose which search algorithm",
        "How to represent graphs in Python",
    ],
})

# ── Lecture 2: Knowledge & Logic ───────────────────────────────────────────
LECTURES.append({
    **lesson_meta(2, "Knowledge & Logic",
        "AI systems need to represent knowledge and reason logically. Learn propositional logic, IF-THEN rules, and inference.",
        50, "Probability & Uncertainty"),
    "sections": [
        {"id": "propositional-logic", "label": "Propositional Logic", "blocks": [
            exp("Propositional Logic",
                "**Propositional logic** deals with statements that are either **True** or **False**. It's the foundation of logical reasoning in AI — the same AND, OR, NOT operators you use in Python.",
                ["Statements have truth values: True or False",
                 "AND (∧) — both must be True",
                 "OR (∨) — at least one must be True",
                 "NOT (¬) — flips True to False and vice versa"]),
            analogy("AND = Needing ID AND Ticket to Enter",
                    "Both conditions must be true to enter an event. If you have an ID but no ticket, you can't get in. AND requires both sides to be True."),
            viz("Logic Operators", "blue",
                left_panel("🎫", "ID AND Ticket", "Both conditions must be true to enter"),
                "AND / OR / NOT",
                "AND: Both True → True\nOR: Either True → True\nNOT True → False\nNOT False → True",
                code="# Python logic operators\nraining = True\noutside = True\nif raining and outside:\n    print('You get wet!')", output="You get wet!"),
            refl("When does AND return True?",
                 "AND returns True only when BOTH sides are True. True AND True = True. Any other combination gives False."),
        ]},
        {"id": "if-then-rules", "label": "IF-THEN Rules", "blocks": [
            exp("IF-THEN Rules",
                "Rules connect conditions to conclusions: **If** it is raining **AND** I am outside, **THEN** I get wet. AI systems use thousands of such rules to make decisions.",
                ["IF condition THEN conclusion",
                 "Multiple conditions can be combined with AND/OR",
                 "Rules form the basis of expert systems",
                 "Same structure as Python if/else statements"]),
            exp("Knowledge Base & Inference",
                "A **Knowledge Base** is a collection of facts and rules. **Inference** is deriving new facts from existing ones — like solving a puzzle clue by clue.",
                ["Knowledge Base = stored facts + rules",
                 "Inference engine applies rules to derive new facts",
                 "Forward chaining: start with facts, apply rules",
                 "Used in medical diagnosis, troubleshooting systems"]),
            analogy("Knowledge Base = A Doctor's Rulebook",
                    "A doctor uses a mental rulebook: IF fever AND cough THEN check for flu. Each symptom adds facts, and rules derive the diagnosis."),
            viz("Knowledge Base & Inference", "purple",
                left_panel("🧩", "Solving Clue by Clue", "Each fact narrows down the answer"),
                "Inference Process",
                "Facts: It is raining\nRule: IF raining AND outside THEN wet\nInference: I am outside → I get wet",
                code="# IF-THEN rule in Python\nif raining and outside:\n    print('You get wet!')\nelif umbrella:\n    print('You stay dry!')", output="You get wet!"),
            refl("What is inference in AI?",
                 "Inference means deriving new facts from existing facts and rules. Given 'Bob owns the dog' and 'Bob has a cat', inference can answer 'What pets does Bob have?'"),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Logic in Practice",
                "Logical reasoning powers expert systems, automated assistants, and decision-making AI.",
                ["Step 1: Define facts (True/False statements)",
                 "Step 2: Write IF-THEN rules connecting facts",
                 "Step 3: Apply inference to derive conclusions",
                 "Step 4: Use conclusions to make decisions"]),
            {"type": "concept_visualization", "title": "How Logical Inference Works", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "📋", "title": "Store Facts", "description": "Add True/False statements to the knowledge base"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Store Facts", "↓", "Apply Rules", "↓", "Derive Conclusions"]},
             "rightPanel": {"label": "Step 3", "emoji": "💡", "title": "Make Decisions", "description": "Use derived facts to answer questions or take action"}},
            code_ex("Three IF-THEN Rules",
                 "raining = True\noutside = True\numbrella = False\n\nif raining and outside and not umbrella:\n    print('You get wet!')\n    print('Go inside!')",
                 "You get wet!\nGo inside!"),
            refl("NOT True equals what?",
                 "NOT True equals False. NOT flips the truth value: NOT False = True."),
            practice("Simulate Daily Life Rules",
                     "Write Python if/else statements for 3 IF-THEN rules about daily life (e.g., weather, school, traffic).",
                     "# Rule 1: If raining and outside, get wet\nraining = True\noutside = True\n# Write your if/else rules",
                     "raining = True\noutside = True\numbrella = False\nif raining and outside and not umbrella:\n    print('You get wet!')\nelif umbrella:\n    print('You stay dry!')",
                     "Use and, or, not just like in propositional logic. Each rule should have a condition and a consequence."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "Propositional logic uses True/False statements"},
        {"emoji": "", "text": "AND requires both sides True; OR requires at least one True"},
        {"emoji": "", "text": "IF-THEN rules connect conditions to conclusions"},
        {"emoji": "", "text": "A Knowledge Base stores facts and rules"},
        {"emoji": "", "text": "Inference derives new facts from existing ones"},
        {"emoji": "", "text": "Logic powers expert systems and automated reasoning"},
    ],
    "whatYouLearned": [
        "How propositional logic works with AND, OR, NOT",
        "How to write IF-THEN rules",
        "What a Knowledge Base is",
        "How inference derives new facts",
        "How to simulate rules in Python",
        "Real-world applications of logical reasoning",
    ],
})

# ── Lecture 3: Probability & Uncertainty ─────────────────────────────────────
LECTURES.append({
    **lesson_meta(3, "Probability & Uncertainty",
        "The real world is rarely clear-cut True or False. Learn probability, conditional probability, and Bayes Theorem.",
        50, "Optimization"),
    "sections": [
        {"id": "why-uncertainty", "label": "Why Uncertainty?", "blocks": [
            exp("Why Uncertainty?",
                "In the real world, information is often **incomplete** or **ambiguous**. AI must handle uncertainty — not everything is simply True or False.",
                ["Weather forecasts say 70% chance of rain — not certain",
                 "Medical tests can be wrong — results are probabilistic",
                 "Spam filters estimate likelihood, not certainty",
                 "Probability gives AI a way to reason under uncertainty"]),
            analogy("Probability = Weather Forecast",
                    "A forecast of 70% chance of rain doesn't mean it will definitely rain. It means rain is likely based on available data — uncertainty expressed as a number."),
            viz("Probability Scale", "blue",
                left_panel("🌧️", "70% Chance of Rain", "Not certain — just likely based on data"),
                "0 to 1 Scale",
                "0 = Impossible (never happens)\n0.5 = Even chance\n1 = Certain (always happens)",
                code="# Probability examples\np_rain = 0.7\np_heads = 0.5\np_impossible = 0.0\nprint(f'Rain chance: {p_rain}')", output="Rain chance: 0.7"),
            refl("What does a probability of 0 mean?",
                 "A probability of 0 means the event is impossible — it will never happen."),
        ]},
        {"id": "conditional-probability", "label": "Conditional Probability", "blocks": [
            exp("Conditional Probability",
                "**Conditional probability** P(X|Y) is the probability of X **given that** Y has already happened. It updates our belief when we learn new information.",
                ["P(rain|cloudy) — chance of rain given cloudy skies",
                 "Knowing Y happened changes the probability of X",
                 "Written as P(X|Y) — 'probability of X given Y'",
                 "Foundation for Bayes Theorem"]),
            exp("Bayes Theorem",
                "**Bayes Theorem** helps AI update beliefs when new evidence arrives: P(H|E) = P(E|H) × P(H) / P(E). A doctor updating diagnosis after test results is Bayes in action.",
                ["Start with a prior belief P(H)",
                 "Observe new evidence E",
                 "Update to posterior belief P(H|E)",
                 "Used in spam filters, medical diagnosis, and AI reasoning"]),
            analogy("Conditional = Knowing It Rained Increases Chance Roads Are Wet",
                    "If you know it rained, the probability of wet roads goes up dramatically. New information changes your estimate."),
            viz("Bayes Theorem in Action", "purple",
                left_panel("🏥", "Doctor Updating Diagnosis", "New test results change the diagnosis probability"),
                "Updating Beliefs",
                "Prior: 10% chance of disease\nEvidence: Positive test\nPosterior: 80% chance of disease\n(Belief updated!)",
                code="# Simplified Bayes\nprior = 0.1\nevidence = 0.9\nposterior = prior * evidence\nprint(f'Updated belief: {posterior}')", output="Updated belief: 0.09"),
            refl("What does Bayes Theorem help with?",
                 "Bayes Theorem helps update beliefs when new evidence arrives. It combines prior knowledge with new observations to compute updated probabilities."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Probability in AI Applications",
                "Probability powers many AI systems you interact with daily.",
                ["Spam filters: P(spam|word patterns in email)",
                 "Medical AI: P(disease|symptoms and test results)",
                 "Recommendation systems: P(like|user history)",
                 "Speech recognition: P(word|audio signal)"]),
            {"type": "concept_visualization", "title": "How Probability AI Works", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "📊", "title": "Observe Evidence", "description": "Collect data about the situation"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Observe Evidence", "↓", "Calculate Probability", "↓", "Make Decision"]},
             "rightPanel": {"label": "Step 3", "emoji": "✅", "title": "Act on Result", "description": "Use probability to choose the best action"}},
            code_ex("Simulate Coin Flips",
                 "import random\nheads = 0\nfor _ in range(100):\n    if random.random() < 0.5:\n        heads += 1\nprint(f'Heads: {heads}/100 = {heads/100}')",
                 "Heads: 52/100 = 0.52"),
            refl("Spam filters use which AI concept?",
                 "Spam filters use probability. They calculate the likelihood an email is spam based on word patterns, then classify accordingly."),
            practice("Coin Flip Simulation",
                     "Write Python to simulate 100 coin flips using the random module and print the probability of heads.",
                     "import random\nheads = 0\n# Simulate 100 flips\n# Count heads and print probability",
                     "import random\nheads = sum(1 for _ in range(100) if random.random() < 0.5)\nprint(f'Probability of heads: {heads/100}')",
                     "Use random.random() < 0.5 to simulate heads. Divide heads count by 100 for probability."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "The real world is uncertain — not always True or False"},
        {"emoji": "", "text": "Probability ranges from 0 (impossible) to 1 (certain)"},
        {"emoji": "", "text": "Conditional probability: P(X given Y already happened)"},
        {"emoji": "", "text": "Bayes Theorem updates beliefs with new evidence"},
        {"emoji": "", "text": "Spam filters and medical AI use probability"},
        {"emoji": "", "text": "Simulations help estimate probabilities experimentally"},
    ],
    "whatYouLearned": [
        "Why AI needs to handle uncertainty",
        "How probability works on a 0 to 1 scale",
        "What conditional probability means",
        "How Bayes Theorem updates beliefs",
        "How spam filters use probability",
        "How to simulate probability with Python",
    ],
})

# ── Lecture 4: Optimization ──────────────────────────────────────────────────
LECTURES.append({
    **lesson_meta(4, "Optimization",
        "Finding the best solution among many options. Learn hill climbing, simulated annealing, and constraint satisfaction.",
        50, "Machine Learning"),
    "sections": [
        {"id": "what-is-optimization", "label": "What is Optimization?", "blocks": [
            exp("What is Optimization?",
                "**Optimization** means finding the **best solution** among many possible options — the cheapest flight, the shortest route, or the best schedule.",
                ["Define an objective: minimize cost or maximize value",
                 "Search through possible solutions",
                 "Find the one that best meets the objective",
                 "Used in logistics, scheduling, and game AI"]),
            analogy("Optimization = Finding the Cheapest Flight",
                    "You compare dozens of flights by price, stops, and time. Optimization algorithms do this systematically to find the best option."),
            viz("Optimization Goal", "blue",
                left_panel("✈️", "Cheapest Flight", "Compare options, pick the best"),
                "Find the Best",
                "Many possible solutions\n↓\nEvaluate each option\n↓\nReturn the best one",
                code="# Find minimum in a list\nprices = [450, 320, 580, 290]\nbest = min(prices)\nprint(f'Best price: ${best}')", output="Best price: $290"),
            refl("What does optimization mean?",
                 "Optimization means finding the best solution among many options — minimizing cost, maximizing value, or satisfying constraints."),
        ]},
        {"id": "hill-climbing", "label": "Hill Climbing", "blocks": [
            exp("Hill Climbing",
                "**Hill climbing** always moves toward a better nearby option — like climbing a hill in fog, always stepping upward. Simple but can get **stuck at a local best**.",
                ["Start at a random solution",
                 "Look at neighboring solutions",
                 "Move to the best neighbor if it's better",
                 "Stop when no neighbor is better (local optimum)"]),
            exp("Simulated Annealing",
                "**Simulated annealing** fixes hill climbing's problem by **occasionally accepting worse options** — helping escape local bests to find the global best.",
                ["Mostly move toward better solutions",
                 "Sometimes accept worse moves (early on)",
                 "Gradually reduce acceptance of worse moves",
                 "Inspired by cooling metal in metallurgy"]),
            analogy("Hill Climbing = Climbing a Hill in Fog",
                    "You always step upward, but fog might hide a taller peak nearby. You get stuck at the top of the hill you're on — a local best, not the global best."),
            viz("Hill Climbing vs Simulated Annealing", "purple",
                left_panel("⛰️", "Climbing in Fog", "Always step up — but may miss the highest peak"),
                "Algorithm Comparison",
                "Hill Climbing:\n• Always move up\n• Gets stuck locally\n\nSimulated Annealing:\n• Usually move up\n• Sometimes step down\n• Finds global best",
                code="# Hill climbing: pick best neighbor\nvalues = [3, 7, 5, 9, 2]\ncurrent = 3\nbest_neighbor = max(values)\nprint(f'Move to: {best_neighbor}')", output="Move to: 9"),
            refl("What problem does hill climbing have?",
                 "Hill climbing can get stuck at a local best — a solution that's better than all neighbors but not the global best. Simulated annealing fixes this by sometimes accepting worse options."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Constraint Satisfaction Problems (CSP)",
                "A **CSP** requires solutions to follow specific **rules** or **constraints**. Sudoku is a classic example — every row, column, and box must contain 1-9 exactly once.",
                ["Variables: things to assign values to",
                 "Domains: possible values for each variable",
                 "Constraints: rules that must be satisfied",
                 "Sudoku, scheduling, and map coloring are CSPs"]),
            analogy("CSP = Scheduling Exams So No Student Has Two at Once",
                    "Each exam slot is a variable, time slots are values, and the constraint is: no student takes two exams simultaneously."),
            {"type": "concept_visualization", "title": "How CSP Solving Works", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "📝", "title": "Define Variables", "description": "List what needs values assigned"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Define Variables", "↓", "Apply Constraints", "↓", "Find Valid Solution"]},
             "rightPanel": {"label": "Example", "code": "# Sudoku constraint:\n# Each row has 1-9 once\n# Each column has 1-9 once\nprint('CSP: rules must be satisfied')", "language": "python", "output": "CSP: rules must be satisfied"}},
            code_ex("Hill Climbing in Python",
                 "values = [4, 1, 7, 3, 9, 2, 8, 5, 6]\ncurrent_idx = 0\nbest = max(values)\nprint(f'Global maximum: {best}')",
                 "Global maximum: 9"),
            refl("Sudoku is an example of what type of problem?",
                 "Sudoku is a Constraint Satisfaction Problem (CSP). Each cell must satisfy row, column, and box constraints simultaneously."),
            practice("Find Maximum by Checking Neighbors",
                     "Write Python to find the maximum value in a list by checking neighbors — simulate hill climbing.",
                     "values = [4, 1, 7, 3, 9, 2, 8, 5, 6]\n# Find the maximum value\n# Hint: use max() or loop through",
                     "values = [4, 1, 7, 3, 9, 2, 8, 5, 6]\nprint(f'Maximum: {max(values)}')",
                     "Hill climbing picks the best neighbor. To find the global max, compare all values using max() or a loop."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "Optimization finds the best solution among many options"},
        {"emoji": "", "text": "Hill climbing always moves up but can get stuck locally"},
        {"emoji": "", "text": "Simulated annealing sometimes accepts worse moves to escape local bests"},
        {"emoji": "", "text": "CSP = Constraint Satisfaction Problem — solutions must follow rules"},
        {"emoji": "", "text": "Sudoku is a classic CSP example"},
        {"emoji": "", "text": "Optimization powers scheduling, logistics, and route planning"},
    ],
    "whatYouLearned": [
        "What optimization means in AI",
        "How hill climbing works and its limitations",
        "How simulated annealing improves on hill climbing",
        "What Constraint Satisfaction Problems are",
        "How to find maximum values in Python",
        "Real-world optimization applications",
    ],
})

# ── Lecture 5: Machine Learning ──────────────────────────────────────────────
LECTURES.append({
    **lesson_meta(5, "Machine Learning",
        "AI that learns rules from examples instead of being programmed. Explore supervised, unsupervised, and reinforcement learning.",
        55, "Neural Networks"),
    "sections": [
        {"id": "what-is-ml", "label": "What is Machine Learning?", "blocks": [
            exp("What is Machine Learning?",
                "**Machine Learning (ML)** is AI that figures out rules from **examples** instead of being told explicit rules. Show it data, and it finds patterns on its own.",
                ["Learns from data, not programmed rules",
                 "Improves with more examples",
                 "Three main types: supervised, unsupervised, reinforcement",
                 "Powers spam filters, recommendations, and image recognition"]),
            analogy("Supervised = Showing a Child Flashcards",
                    "You show flashcards with the correct answer until they learn. Supervised learning uses labeled examples — input paired with the correct output."),
            viz("Machine Learning Overview", "blue",
                left_panel("📚", "Learning from Examples", "Show data, AI finds patterns"),
                "ML Types",
                "Supervised: labeled data\nUnsupervised: find patterns\nReinforcement: rewards/penalties",
                code="# ML learns from data\n# Not: if x > 5: spam\n# But: learn from 1000s of emails\nprint('ML finds patterns in data')", output="ML finds patterns in data"),
            refl("ML learns rules from what?",
                 "ML learns rules from examples and data — not from explicit programming. The more quality data, the better the model learns."),
        ]},
        {"id": "supervised-unsupervised", "label": "Supervised & Unsupervised", "blocks": [
            exp("Supervised Learning",
                "**Supervised learning** uses **labeled examples** — each input comes with the correct output. Like flashcards with answers on the back.",
                ["Training data has input + correct output pairs",
                 "Classification: predict categories (spam/not spam)",
                 "Regression: predict numbers (house prices)",
                 "Examples: spam filters, image classification"]),
            exp("Unsupervised Learning",
                "**Unsupervised learning** finds **patterns without labels** — grouping similar items without being told the categories.",
                ["No correct answers provided",
                 "Clustering: group similar items together",
                 "Finding hidden structure in data",
                 "Examples: customer grouping, song genre discovery"]),
            analogy("Unsupervised = Grouping Similar Songs Without Genre Labels",
                    "Without being told genres, unsupervised learning groups songs by similarity — tempo, instruments, mood — discovering patterns on its own."),
            viz("Supervised vs Unsupervised", "purple",
                left_panel("🎵", "Grouping Songs", "Find patterns without being told genres"),
                "Learning Comparison",
                "Supervised:\n• Has labels\n• Learns input→output\n• Spam filter, classification\n\nUnsupervised:\n• No labels\n• Finds clusters\n• Customer grouping",
                code="# Supervised: labeled\n# email → spam/not spam\n\n# Unsupervised: unlabeled\n# group customers by behavior", output="Different learning approaches"),
            refl("What does overfitting mean?",
                 "Overfitting means the model memorizes training data but fails on new data. It learned the training examples too specifically instead of general patterns."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Reinforcement Learning",
                "**Reinforcement learning** learns by **trying, failing, and getting rewards** — like training a dog with treats for correct behavior and ignoring wrong behavior.",
                ["Agent takes actions in an environment",
                 "Receives rewards for good actions, penalties for bad",
                 "Learns policy: which action to take in each state",
                 "Examples: chess AI, game-playing, robotics"]),
            analogy("Reinforcement = Training a Dog",
                    "Reward correct behavior, ignore wrong behavior. Over time, the dog learns which actions earn treats. RL agents learn the same way through trial and error."),
            {"type": "concept_visualization", "title": "How Reinforcement Learning Works", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "🎮", "title": "Agent Takes Action", "description": "The AI tries something in its environment"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Take Action", "↓", "Get Reward/Penalty", "↓", "Improve Strategy"]},
             "rightPanel": {"label": "Code Example", "code": "# Simple classifier\nnum = int(input())\nif num > 0:\n    print('positive')\nelif num < 0:\n    print('negative')\nelse:\n    print('zero')", "language": "python", "output": "positive"}},
            code_ex("Simple Classifier",
                 "num = 5\nif num > 0:\n    label = 'positive'\nelif num < 0:\n    label = 'negative'\nelse:\n    label = 'zero'\nprint(label)",
                 "positive"),
            refl("Unsupervised learning finds what?",
                 "Unsupervised learning finds patterns without labels — grouping similar data points or discovering hidden structure in unlabeled datasets."),
            practice("Build a Simple Classifier",
                     "Write Python to classify a number as positive, negative, or zero — simulate a simple classifier.",
                     "num = 0  # Try different values\n# Classify as positive, negative, or zero",
                     "num = -3\nif num > 0:\n    print('positive')\nelif num < 0:\n    print('negative')\nelse:\n    print('zero')",
                     "Use if/elif/else with > 0, < 0, and == 0 comparisons."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "ML learns rules from examples/data, not explicit programming"},
        {"emoji": "", "text": "Supervised learning requires labeled training data"},
        {"emoji": "", "text": "Unsupervised learning finds patterns without labels"},
        {"emoji": "", "text": "Reinforcement learning uses rewards and penalties"},
        {"emoji": "", "text": "Overfitting = memorizing training data, failing on new data"},
        {"emoji": "", "text": "ML powers spam filters, recommendations, and game AI"},
    ],
    "whatYouLearned": [
        "What Machine Learning is and how it differs from traditional programming",
        "The three types of ML: supervised, unsupervised, reinforcement",
        "What overfitting means and why it matters",
        "How to build a simple classifier in Python",
        "Real-world ML applications",
        "How reinforcement learning uses rewards",
    ],
})

# ── Lecture 6: Neural Networks ───────────────────────────────────────────────
LECTURES.append({
    **lesson_meta(6, "Neural Networks",
        "Computing systems inspired by the human brain. Learn how nodes, weights, and layers power deep learning and image recognition.",
        55, "Natural Language Processing"),
    "sections": [
        {"id": "what-is-nn", "label": "What is a Neural Network?", "blocks": [
            exp("What is a Neural Network?",
                "A **neural network** is a system of **connected nodes** inspired by neurons in the human brain. Each node processes inputs and passes results to the next layer.",
                ["Inspired by biological neurons in the brain",
                 "Nodes connected in layers",
                 "Each connection has a weight (importance)",
                 "Training adjusts weights based on examples"]),
            analogy("Neural Network = Team Passing Notes",
                    "Each person reads a note, adds their opinion, and passes it to the next person. Weights determine how much you trust each person's input."),
            viz("Neural Network Structure", "blue",
                left_panel("📝", "Passing Notes", "Each person processes and passes to the next"),
                "Network Layers",
                "Input Layer → Hidden Layers → Output Layer\n\nEach node: inputs × weights → output",
                code="# One node calculation\ninput1 = 0.8\ninput2 = 0.6\nweight1 = 0.5\nweight2 = 0.3\noutput = input1*weight1 + input2*weight2\nprint(output)", output="0.58"),
            refl("Neural networks are inspired by what?",
                 "Neural networks are inspired by the human brain — specifically how biological neurons connect and process signals through weighted connections."),
        ]},
        {"id": "nodes-layers", "label": "Nodes & Layers", "blocks": [
            exp("How a Node Works",
                "Each node takes **inputs**, multiplies each by a **weight** (how much that input matters), sums them up, and produces an **output**.",
                ["Input × Weight for each connection",
                 "Sum all weighted inputs",
                 "Apply activation function",
                 "Pass output to next layer"]),
            exp("Layers: Input → Hidden → Output",
                "Networks are organized in **layers**: Input Layer receives data, Hidden Layers process it, Output Layer produces the final prediction.",
                ["Input Layer: receives raw data (pixels, numbers)",
                 "Hidden Layers: extract features and patterns",
                 "Output Layer: produces final prediction",
                 "More hidden layers = 'deeper' network = Deep Learning"]),
            analogy("Weights = How Much You Trust Each Person's Opinion",
                    "In a team decision, some people's opinions matter more. Weights work the same way — they control how much each input influences the output."),
            viz("Layers in a Neural Network", "purple",
                left_panel("⚖️", "Trust Levels", "Some inputs matter more than others"),
                "Layer Flow",
                "Input Layer (data in)\n    ↓\nHidden Layer(s) (process)\n    ↓\nOutput Layer (prediction)",
                code="# 3-layer network for pass/fail\nattendance = 0.9\nmarks = 0.75\nw1, w2 = 0.4, 0.6\nscore = attendance*w1 + marks*w2\nprint('Pass' if score > 0.5 else 'Fail')", output="Pass"),
            refl("What are weights in a neural network?",
                 "Weights are numbers that control how much each input matters to a node's output. Training adjusts weights so the network makes better predictions."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Deep Learning & CNNs",
                "**Deep Learning** uses neural networks with **many hidden layers**. **CNNs (Convolutional Neural Networks)** are specialized for **image recognition** — detecting edges, shapes, and objects.",
                ["Deep Learning = many hidden layers",
                 "Each layer learns increasingly complex features",
                 "CNNs: specialized for images and visual data",
                 "Powers face recognition, medical imaging, self-driving cars"]),
            {"type": "concept_visualization", "title": "How Deep Learning Processes Images", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "🖼️", "title": "Input Image", "description": "Raw pixel data enters the input layer"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Detect Edges", "↓", "Find Shapes", "↓", "Recognize Object"]},
             "rightPanel": {"label": "Code Example", "code": "# Weighted sum of two inputs\na, b = 0.8, 0.6\nw1, w2 = 0.5, 0.3\nresult = a*w1 + b*w2\nprint(f'Node output: {result}')", "language": "python", "output": "Node output: 0.58"}},
            code_ex("Calculate Weighted Sum",
                 "attendance = 0.9\nmarks = 0.75\nweight_attendance = 0.4\nweight_marks = 0.6\noutput = attendance * weight_attendance + marks * weight_marks\nprint(f'Score: {output}')",
                 "Score: 0.81"),
            refl("CNNs are best for what type of task?",
                 "CNNs (Convolutional Neural Networks) are best for image recognition — detecting patterns in visual data like photos and videos."),
            practice("Simulate One Neural Network Node",
                     "Write Python to calculate a weighted sum of two inputs — simulate one neural network node.",
                     "input1 = 0.8\ninput2 = 0.6\nweight1 = 0.5\nweight2 = 0.3\n# Calculate weighted sum",
                     "input1 = 0.8\ninput2 = 0.6\nweight1 = 0.5\nweight2 = 0.3\noutput = input1 * weight1 + input2 * weight2\nprint(f'Node output: {output}')",
                     "Multiply each input by its weight, then add them together: output = input1×weight1 + input2×weight2"),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "Neural networks are inspired by the human brain"},
        {"emoji": "", "text": "Each node: inputs × weights → output"},
        {"emoji": "", "text": "Layers: Input → Hidden → Output"},
        {"emoji": "", "text": "Deep Learning uses many hidden layers"},
        {"emoji": "", "text": "CNNs are specialized for image recognition"},
        {"emoji": "", "text": "Training adjusts weights after seeing thousands of examples"},
    ],
    "whatYouLearned": [
        "What neural networks are and how they're structured",
        "How individual nodes process weighted inputs",
        "The role of input, hidden, and output layers",
        "What Deep Learning and CNNs are",
        "How to calculate a weighted sum in Python",
        "Real-world applications of neural networks",
    ],
})

# ── Lecture 7: Natural Language Processing ───────────────────────────────────
LECTURES.append({
    **lesson_meta(7, "Natural Language Processing",
        "AI that understands and generates human language. Learn tokenization, word embeddings, and large language models.",
        55, "AI Ethics & Responsible Use"),
    "sections": [
        {"id": "what-is-nlp", "label": "What is NLP?", "blocks": [
            exp("What is Natural Language Processing?",
                "**Natural Language Processing (NLP)** is AI that understands, interprets, and generates **human language** — text and speech.",
                ["Powers chatbots, translation, and voice assistants",
                 "Converts human language to numbers AI can process",
                 "Enables search engines to understand queries",
                 "Foundation for GPT, Gemini, and Claude"]),
            analogy("Tokenization = Breaking a Sentence into Puzzle Pieces",
                    "Before solving a puzzle, you sort the pieces. Tokenization splits text into smaller units (words or subwords) that AI can process one at a time."),
            viz("NLP Pipeline", "blue",
                left_panel("🧩", "Puzzle Pieces", "Break text into processable units"),
                "NLP Steps",
                "Text Input\n↓\nTokenization\n↓\nWord Embeddings\n↓\nLanguage Model\n↓\nOutput",
                code="# Tokenize a sentence\ntext = 'AI is amazing'\ntokens = text.split()\nprint(tokens)", output="['AI', 'is', 'amazing']"),
            refl("NLP stands for what?",
                 "NLP stands for Natural Language Processing — the field of AI focused on understanding and generating human language."),
        ]},
        {"id": "tokenization-embeddings", "label": "Tokenization & Embeddings", "blocks": [
            exp("Tokenization",
                "**Tokenization** splits text into smaller units — words, subwords, or characters — that AI can process individually.",
                ["Breaks 'Hello world' into ['Hello', 'world']",
                 "Different tokenizers for different languages",
                 "First step in any NLP pipeline",
                 "LLMs tokenize before processing"]),
            exp("Word Embeddings",
                "**Word embeddings** represent words as **numbers (vectors)** so AI can find similarities — similar words are placed close together on a mathematical map.",
                ["Each word becomes a list of numbers (vector)",
                 "'King' and 'Queen' have similar vectors",
                 "'King' - 'Man' + 'Woman' ≈ 'Queen'",
                 "Enables AI to understand word relationships"]),
            analogy("Word Embeddings = Words on a Map Where Similar Words Are Close",
                    "On a map, cities near each other are close together. Word embeddings place similar words close in vector space — 'happy' near 'joyful', far from 'sad'."),
            viz("Word Embeddings", "purple",
                left_panel("🗺️", "Word Map", "Similar words placed close together"),
                "Vectors",
                "happy  → [0.8, 0.9, 0.1]\njoyful → [0.7, 0.85, 0.15]\nsad    → [0.1, 0.2, 0.9]\n(similar vectors = similar meaning)",
                code="# Word frequency count\nfrom collections import Counter\ntext = 'AI is great and AI is fun'\nwords = text.lower().split()\nprint(Counter(words))", output="Counter({'ai': 2, 'is': 2, 'great': 1, 'and': 1, 'fun': 1})"),
            refl("Word embeddings represent words as what?",
                 "Word embeddings represent words as numbers (vectors) — lists of numeric values that capture meaning and similarity between words."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Language Models & LLMs",
                "**Language models** predict the next word in a sequence. **LLMs (Large Language Models)** like GPT, Gemini, and Claude are trained on vast text to generate human-like responses.",
                ["Predict next word based on context",
                 "GPT, Gemini, Claude are LLMs",
                 "Transformers process all words in parallel",
                 "Powers chatbots, writing assistants, code generation"]),
            analogy("LLM = An Extremely Well-Read Person",
                    "Imagine someone who has read the entire internet. They can answer questions, write stories, and explain concepts — that's essentially what an LLM does."),
            {"type": "concept_visualization", "title": "How LLMs Generate Text", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "💬", "title": "User Input", "description": "Your question or prompt enters the model"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Tokenize Input", "↓", "Predict Next Token", "↓", "Generate Response"]},
             "rightPanel": {"label": "Code Example", "code": "text = 'AI is the future'\nwords = text.split()\nfrom collections import Counter\ncounts = Counter(words)\nprint(dict(counts))", "language": "python", "output": "{'AI': 1, 'is': 1, 'the': 1, 'future': 1}"}},
            code_ex("Count Word Frequencies",
                 "from collections import Counter\nsentence = 'AI helps AI learn and AI grows'\nwords = sentence.lower().split()\nfor word, count in Counter(words).items():\n    print(f'{word}: {count}')",
                 "ai: 3\nhelps: 1\nlearn: 1\nand: 1\ngrows: 1"),
            refl("Transformers process words how?",
                 "Transformers process all words at once (in parallel), not one at a time. This makes them much faster and more effective than earlier sequential models."),
            practice("Tokenize and Count Words",
                     "Write Python to tokenize a sentence (split into words) and count how many times each word appears.",
                     "from collections import Counter\nsentence = 'Machine learning is powerful and learning is fun'\n# Split into words and count",
                     "from collections import Counter\nsentence = 'Machine learning is powerful and learning is fun'\nwords = sentence.lower().split()\nprint(dict(Counter(words)))",
                     "Use .split() to tokenize and Counter() from collections to count word frequencies."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "NLP enables AI to understand and generate human language"},
        {"emoji": "", "text": "Tokenization splits text into processable units"},
        {"emoji": "", "text": "Word embeddings represent words as number vectors"},
        {"emoji": "", "text": "LLMs predict next words — powering GPT, Gemini, Claude"},
        {"emoji": "", "text": "Transformers process all words in parallel"},
        {"emoji": "", "text": "NLP powers chatbots, translation, and search"},
    ],
    "whatYouLearned": [
        "What Natural Language Processing is",
        "How tokenization breaks text into units",
        "How word embeddings capture meaning",
        "What language models and LLMs are",
        "How to tokenize and count words in Python",
        "Real-world NLP applications",
    ],
})

# ── Lecture 8: AI Ethics ─────────────────────────────────────────────────────
LECTURES.append({
    **lesson_meta(8, "AI Ethics & Responsible Use",
        "With great AI power comes great responsibility. Learn about bias, privacy, hallucinations, deepfakes, and accountability.",
        50, "Final Project"),
    "sections": [
        {"id": "ai-bias", "label": "AI Bias", "blocks": [
            exp("AI Bias",
                "**AI bias** occurs when training data is unfair or unrepresentative — the AI inherits and **amplifies** those biases in its decisions.",
                ["Biased training data → biased AI outputs",
                 "Example: hiring AI trained mostly on male resumes",
                 "Facial recognition less accurate for some demographics",
                 "Bias can harm marginalized groups"],
                accent="blue"),
            analogy("Bias = Learning From Only One Group",
                    "If you only learn opinions from one group of people, your views will be skewed. AI trained on biased data makes skewed decisions."),
            viz("How Bias Enters AI", "blue",
                left_panel("👥", "One-Sided Learning", "Limited perspectives create skewed opinions"),
                "Bias Pipeline",
                "Biased Data\n↓\nBiased Model\n↓\nUnfair Decisions\n↓\nHarm to Users",
                code="# Bias example:\n# Training data: 90% one group\n# Model favors that group\nprint('Diverse data = fairer AI')", output="Diverse data = fairer AI"),
            refl("AI bias comes from what?",
                 "AI bias comes from unfair or unrepresentative training data. If the data doesn't represent all groups fairly, the AI will make biased decisions."),
        ]},
        {"id": "privacy-hallucinations", "label": "Privacy & Hallucinations", "blocks": [
            exp("Privacy Concerns",
                "AI systems **collect vast amounts of data** about users. Without proper safeguards, this data can be misused, leaked, or used without consent.",
                ["AI collects browsing, location, and personal data",
                 "Users often don't know what data is collected",
                 "Data breaches can expose sensitive information",
                 "Privacy laws like GDPR aim to protect users"]),
            exp("AI Hallucinations",
                "An **AI hallucination** is when AI **confidently states wrong facts** — making up information that sounds plausible but is completely false.",
                ["LLMs can generate false but convincing text",
                 "No built-in fact-checking in most models",
                 "Dangerous in medical, legal, or news contexts",
                 "Always verify AI-generated facts"]),
            analogy("Hallucination = A Confident Student Making Up Answers",
                    "A student who doesn't know the answer but speaks confidently anyway — sounding sure while being completely wrong. That's an AI hallucination."),
            viz("Hallucinations vs Facts", "purple",
                left_panel("🎓", "Confident but Wrong", "Sounds sure but makes things up"),
                "Hallucination",
                "User: 'Who invented the lightbulb?'\nAI: 'John Smith in 1892' ← WRONG!\n(Confident but fabricated)",
                code="# Always verify AI outputs\nai_response = 'Some fact from AI'\nprint('Verify before trusting!')", output="Verify before trusting!"),
            refl("AI hallucination means what?",
                 "AI hallucination means the AI states wrong facts confidently — generating plausible-sounding but false information."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("Deepfakes & Misinformation",
                "**Deepfakes** use AI to generate **fake videos and audio** that look and sound real — enabling misinformation and fraud.",
                ["AI-generated fake videos of real people",
                 "Synthetic voices mimicking anyone",
                 "Used for fraud, political manipulation",
                 "Hard to detect with the naked eye"]),
            exp("Accountability & Fairness",
                "When AI causes harm, **who is responsible** — the developer, the company, or the user? **Transparency** means people should know when they're interacting with AI.",
                ["Shared responsibility: developers, companies, users",
                 "Transparency: disclose when content is AI-generated",
                 "Fairness: AI should treat all groups equitably",
                 "Regulation evolving to address AI harms"]),
            analogy("Accountability = Self-Driving Car Crash — Who Is Responsible?",
                    "If a self-driving car crashes, is it the driver, the car company, or the AI developer? AI accountability is one of the hardest ethical questions."),
            {"type": "concept_visualization", "title": "Responsible AI Framework", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "🔍", "title": "Identify Risks", "description": "Find bias, privacy, and safety concerns"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Identify Risks", "↓", "Mitigate Harm", "↓", "Ensure Transparency"]},
             "rightPanel": {"label": "Principle", "code": "# Responsible AI checklist:\n# 1. Fair training data\n# 2. Privacy protection\n# 3. Transparency\n# 4. Human oversight\nprint('Build AI responsibly')", "language": "python", "output": "Build AI responsibly"}},
            refl("Who is responsible when AI causes harm?",
                 "Responsibility is shared among developers (who build the system), companies (who deploy it), and users (who use it). All parties have ethical obligations."),
            practice("Reflect on AI Ethics",
                     "Write 3 sentences about one ethical issue in AI (bias, privacy, or hallucinations) and how you would address it.",
                     "# Ethical issue:\n# My concern:\n# How I would address it:\nprint('Issue: AI bias in hiring')\nprint('Concern: Unfair rejections')\nprint('Fix: Diverse training data')",
                     "print('Issue: AI hallucinations in medical advice')\nprint('Concern: Wrong diagnoses')\nprint('Fix: Always require doctor verification')",
                     "Pick one ethical issue from this lecture. Write what concerns you and one concrete step to address it."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "AI bias comes from unfair or unrepresentative training data"},
        {"emoji": "", "text": "AI hallucination = confidently stating wrong facts"},
        {"emoji": "", "text": "Deepfakes use AI to generate fake videos/audio"},
        {"emoji": "", "text": "Transparency: people should know when they interact with AI"},
        {"emoji": "", "text": "Accountability is shared: developers, companies, and users"},
        {"emoji": "", "text": "Responsible AI requires proactive ethical consideration"},
    ],
    "whatYouLearned": [
        "How AI bias enters systems through training data",
        "What AI hallucinations are and why they're dangerous",
        "How deepfakes enable misinformation",
        "Why privacy matters in AI systems",
        "Who is accountable when AI causes harm",
        "How to think critically about AI ethics",
    ],
})

# ── Lecture 9: Final Project ─────────────────────────────────────────────────
LECTURES.append({
    **lesson_meta(9, "Final Project",
        "Apply everything you've learned in a capstone AI project. Choose your project, plan it, and reflect on your AI journey.",
        60, None),
    "sections": [
        {"id": "what-you-learned", "label": "What You Have Learned", "blocks": [
            exp("Your AI Journey",
                "Congratulations! You've covered the **7 core AI topics** that form the foundation of modern artificial intelligence.",
                ["**Search** — finding paths from start to goal",
                 "**Knowledge** — logical reasoning with facts and rules",
                 "**Uncertainty** — probability and Bayes Theorem",
                 "**Optimization** — finding the best solution",
                 "**Learning** — ML from data (supervised, unsupervised, reinforcement)",
                 "**Neural Networks** — brain-inspired deep learning",
                 "**Language** — NLP and large language models"]),
            analogy("Your AI Toolkit Is Complete",
                    "Like a craftsman with a full toolbox, you now have search, logic, probability, optimization, ML, neural networks, and NLP — ready to build real AI projects."),
            viz("The 7 Core AI Topics", "blue",
                left_panel("🎓", "Complete Toolkit", "All 7 AI topics mastered"),
                "CS50 AI Curriculum",
                "1. Search Algorithms\n2. Knowledge & Logic\n3. Probability\n4. Optimization\n5. Machine Learning\n6. Neural Networks\n7. Natural Language Processing",
                code="# Your AI toolkit:\ntopics = ['Search', 'Knowledge', 'Uncertainty',\n          'Optimization', 'ML', 'Neural Nets', 'NLP']\nfor t in topics:\n    print(f'✓ {t}')", output="✓ Search\n✓ Knowledge\n..."),
            refl("Which AI concept does a chatbot primarily use?",
                 "A chatbot primarily uses NLP (Natural Language Processing) to understand user input and generate responses, often powered by language models."),
        ]},
        {"id": "choose-project", "label": "Choosing Your Project", "blocks": [
            exp("Four Project Options",
                "Choose one capstone project that demonstrates an AI concept you've learned.",
                ["**AI Chatbot** — converses on a topic using NLP",
                 "**AI Story Generator** — creates stories using language models",
                 "**AI Resume Builder** — suggests improvements using NLP",
                 "**Search Visualizer** — visualizes BFS/DFS/A* algorithms"]),
            exp("What Your Project Must Show",
                "Every project must demonstrate understanding of an AI concept and include thoughtful ethical consideration.",
                ["Clear AI concept being demonstrated",
                 "User input and AI output defined",
                 "Working implementation (code or activity)",
                 "At least one ethical consideration addressed"]),
            analogy("Your Project = Showing What You Can Build",
                    "A portfolio piece that proves you understand AI — not just theory, but practical application with ethical awareness."),
            viz("Project Planning Template", "purple",
                left_panel("📋", "Project Plan", "Define concept, input, output, ethics"),
                "Project Structure",
                "1. AI Concept Used\n2. User Input\n3. AI Output\n4. Ethical Consideration\n5. Reflection",
                code="# Project plan template\nconcept = 'NLP'\nuser_input = 'Ask a question'\nai_output = 'Generate answer'\nethics = 'Check for bias'\nprint(f'Project uses: {concept}')", output="Project uses: NLP"),
            refl("What must every project include?",
                 "Every project must include an ethical consideration — thinking about bias, privacy, fairness, or transparency relevant to your chosen project."),
        ]},
        {"id": "getting-started", "label": "Getting Started", "blocks": [
            exp("How to Present Your Project",
                "Structure your project presentation to show both technical understanding and personal reflection.",
                ["Demo: show your project working",
                 "Explain: which AI concept it uses and why",
                 "Ethics: what ethical issue you considered",
                 "Reflection: what surprised you about how AI works"]),
            {"type": "concept_visualization", "title": "Project Presentation Flow", "accentColor": "green",
             "leftPanel": {"label": "Step 1", "emoji": "🎯", "title": "Choose Project", "description": "Pick chatbot, story generator, resume builder, or search visualizer"},
             "centerPanel": {"label": "Step 2", "visualType": "flow_diagram",
                             "flowSteps": ["Choose Project", "↓", "Build & Test", "↓", "Present & Reflect"]},
             "rightPanel": {"label": "Step 3", "emoji": "🏆", "title": "Lecture Complete!", "description": "Share what you built and what you learned about AI"}},
            exp("Final Reflection Questions",
                "Your reflection should explore what surprised you most about how AI works.",
                ["What AI concept was most surprising to learn?",
                 "What ethical issue concerns you most?",
                 "How will you use AI responsibly going forward?",
                 "What would you build next with your AI knowledge?"]),
            refl("Final reflection should cover what?",
                 "Final reflection should cover what surprised you about how AI works — the insights and discoveries that changed your understanding of artificial intelligence."),
            practice("Write Your Project Plan",
                     "Choose one project and write a plan: what AI concept it uses, what input the user gives, and what output the AI produces.",
                     "# My project choice:\n# AI concept:\n# User input:\n# AI output:\n# Ethical consideration:\nprint('Project: AI Chatbot')\nprint('Concept: NLP')",
                     "print('Project: Search Visualizer')\nprint('Concept: Search Algorithms (BFS/DFS/A*)')\nprint('Input: Grid maze configuration')\nprint('Output: Visual path animation')\nprint('Ethics: Ensure algorithm fairness')",
                     "Pick one of the four project options. Fill in each field of the project plan template."),
        ]},
    ],
    "keyTakeaways": [
        {"emoji": "", "text": "AI is computers doing tasks that need human-like thinking"},
        {"emoji": "", "text": "Search, Knowledge, Uncertainty, Optimization, Learning, Neural Networks, Language"},
        {"emoji": "", "text": "ML learns from data — supervised, unsupervised, reinforcement"},
        {"emoji": "", "text": "Neural networks power Deep Learning and image recognition"},
        {"emoji": "", "text": "NLP powers LLMs like GPT, Gemini, and Claude"},
        {"emoji": "", "text": "Responsible AI requires awareness of bias, privacy, and accountability"},
    ],
    "whatYouLearned": [
        "All 7 core AI topics from the CS50 AI curriculum",
        "How to choose and plan a capstone AI project",
        "What ethical considerations every AI project needs",
        "How to structure a project presentation",
        "How to reflect on your AI learning journey",
        "That responsible AI development is everyone's responsibility",
    ],
})


# ── Write all lessons ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    for lec in LECTURES:
        num = lec.pop("number")
        next_up = lec.pop("nextUp", None)
        key_takeaways = lec.pop("keyTakeaways")
        what_learned = lec.pop("whatYouLearned")
        lec["number"] = num
        lec["summary"] = {
            "keyTakeaways": key_takeaways,
            "whatYouLearned": what_learned,
        }
        if next_up:
            lec["summary"]["nextUp"] = next_up
        write_lesson(num, lec)
    print(f"\nGenerated {len(LECTURES)} CS50 AI lectures.")

